graphhopper:
  datareader.file: /data/map.osm.pbf
  graph.location: /data/graph-cache

  profiles:
    - name: car
      custom_model_files: [car.json]
    - name: car_custom
      custom_model_files: [car.json]
    - name: bike
      custom_model_files: [bike.json]
    - name: foot
      custom_model_files: [foot.json]

  # CH: schnelles Routing für Standard-Car-Anfragen
  profiles_ch:
    - profile: car

  # car_custom läuft ohne CH → Custom Model per Anfrage möglich

server:
  application_connectors:
    - type: http
      port: 8989
      bind_host: 0.0.0.0
  admin_connectors:
    - type: http
      port: 8990
      bind_host: 0.0.0.0
